# https://docs.gitlab.com/ce/ci/yaml/
stages:
  - check
  - test
  - coverage

check-style:
  stage: check
  image: node:7.10.0
  services:
  variables:
    ENV: development
  before_script:
    - node --version
    - npm --version
    - npm install -g eslint
  script:
    - eslint lib
  cache:
    untracked: true
    paths:
      - node_modules
  except:
    - tags

run-test:
  stage: test
  image: node:7.10.0
  services:
  variables:
    NODE_ENV: development
  before_script:
    - node --version
    - npm --version
    - npm install
  script:
    - node_modules/.bin/gulp test
  cache:
    untracked: true
    paths:
      - node_modules
  except:
    - tags

run-coverage:
  stage: coverage
  image: node:7.10.0
  services:
  variables:
    NODE_ENV: development
  before_script:
    - node --version
    - npm --version
    - npm install
  script:
    - npm test
  cache:
    untracked: true
    paths:
      - node_modules
  except:
    - tags
